server:    
  port: 8001
 
# 定义当前服务名
spring:
   application:
     name: user

# 配置Eureka 服务器的地址
eureka:
  client:
       serviceUrl:
          defaultZone: http://es1:8000/eureka
          
# 开启声明式服务降级   
feign:
  hystrix:
    enabled: true   
---
server:
    port: 8005
 # 配置块名
spring:
   profiles: user8005        
       
---
server:
    port: 8006
 # 配置块名
spring:
   profiles: user8006        
        